export const environment = {
  production: true,
  name: 'Heriken',
  domain: 'heriken.co',
  apiBaseLink: 'https://api.heriken.co',
  ftpBaseLink: 'https://api.heriken.co',
  appBaseUrl: '/',
  userBaseUrl: '/',
  userProfileUrl: '/my-profile',
  userLoginUrl: '/login',
  vendorBaseUrl: 'vendor',
  vendorLoginUrl: 'vendor/login',
  adminLoginUrl: 'admin/login',
  adminBaseUrl: 'admin',
  storageSecret: 'SOFT_2021_IT_1998',
  adminTokenSecret: 'SOFT_ADMIN_1995_&&_SOJOL_dEv',
  userTokenSecret: 'SOFT_ADMIN_1996_&&_SOBUR_dEv',
  apiTokenSecret: 'SOFT_API_1998_&&_SAZIB_dEv',
  VERSION: 1
};
